"""p01_customer_clean.py - generated by convert_rules.py (rule-based, deterministic) from sas/programs/01_customer_clean.sas."""

from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F

spark = SparkSession.builder.master("local[*]").appName("01_customer_clean").getOrCreate()
LIB = {'ctrl': 'data/parquet/ctrl', 'stg': 'data/parquet/stg', 'out': 'data/parquet/py_out/rule_based/run1'}
work = {}  # SAS WORK tables live in memory


def read(lib, table):
    """A table of a SAS library: migrated Parquet (ctrl, stg), a converted output (out) or WORK."""
    if lib == "work":
        return work[table]
    path = f"{LIB[lib]}/{table}" + (".parquet" if lib in ("ctrl", "stg") else "")
    return spark.read.parquet(path)


def save(df, lib, table):
    """Write an `out` table as Parquet; keep a WORK table in memory."""
    if lib == "work":
        work[table] = df
    else:
        df.write.mode("overwrite").parquet(f"{LIB[lib]}/{table}")

# ---- data out.customers_clean
df = read("stg", "customers")
df = df.withColumn("customer_name", F.trim(F.col("customer_name")))
df = df.withColumn("province", F.upper(F.col("province")))
df = df.withColumn("income_missing", F.col("annual_income").isNull().cast('int'))
df = df.withColumn("income_band", F.when((F.col("annual_income").isNull() | (F.col("annual_income") < 20000)), F.lit('LOW')).when((F.col("annual_income").isNull() | (F.col("annual_income") < 80000)), F.lit('MID')).otherwise(F.lit('HIGH')))
save(df, "out", "customers_clean")
