"""p02_loan_enrichment.py - generated by convert_rules.py (rule-based, deterministic) from sas/programs/02_loan_enrichment.sas."""

from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F

spark = SparkSession.builder.master("local[*]").appName("02_loan_enrichment").getOrCreate()
LIB = {'ctrl': 'data/parquet/ctrl', 'stg': 'data/parquet/stg', 'out': 'data/parquet/py_out/rule_based/run1'}
work = {}  # SAS WORK tables live in memory


def read(lib, table):
    """A table of a SAS library: migrated Parquet (ctrl, stg), a converted output (out) or WORK."""
    if lib == "work":
        return work[table]
    path = f"{LIB[lib]}/{table}" + (".parquet" if lib in ("ctrl", "stg") else "")
    return spark.read.parquet(path)


def save(df, lib, table):
    """Write an `out` table as Parquet; keep a WORK table in memory."""
    if lib == "work":
        work[table] = df
    else:
        df.write.mode("overwrite").parquet(f"{LIB[lib]}/{table}")

# ---- proc sql
read("ctrl", "client_segments").createOrReplaceTempView("ctrl__client_segments")
read("out", "customers_clean").createOrReplaceTempView("out__customers_clean")
read("stg", "loans").createOrReplaceTempView("stg__loans")
df = spark.sql('select l.*, c.customer_name, c.province, c.income_band, s.segment_name, s.risk_band from stg__loans as l inner join out__customers_clean as c on l.customer_id = c.customer_id left join ctrl__client_segments as s on c.segment_code = s.segment_code')
save(df, "out", "loan_enriched")
