"""p03_risk_format.py - generated by convert_rules.py (rule-based, deterministic) from sas/programs/03_risk_format.sas."""

from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F

spark = SparkSession.builder.master("local[*]").appName("03_risk_format").getOrCreate()
LIB = {'ctrl': 'data/parquet/ctrl', 'stg': 'data/parquet/stg', 'out': 'data/parquet/py_out/rule_based/run1'}
work = {}  # SAS WORK tables live in memory


def read(lib, table):
    """A table of a SAS library: migrated Parquet (ctrl, stg), a converted output (out) or WORK."""
    if lib == "work":
        return work[table]
    path = f"{LIB[lib]}/{table}" + (".parquet" if lib in ("ctrl", "stg") else "")
    return spark.read.parquet(path)


def save(df, lib, table):
    """Write an `out` table as Parquet; keep a WORK table in memory."""
    if lib == "work":
        work[table] = df
    else:
        df.write.mode("overwrite").parquet(f"{LIB[lib]}/{table}")

# ---- proc format
# (format translated into the expressions that use it)

# ---- data out.customer_risk
df = read("out", "customers_clean")
df = df.withColumn("income_band_fmt", F.when(F.col("annual_income").isNotNull() & (F.col("annual_income") < 20000), F.lit('LOW')).when(F.col("annual_income").isNotNull() & (F.col("annual_income") >= 20000) & (F.col("annual_income") < 80000), F.lit('MID')).when(F.col("annual_income").isNotNull() & (F.col("annual_income") >= 80000), F.lit('HIGH')).otherwise(F.lit('UNKNOWN')))
save(df, "out", "customer_risk")
