"""p05_card_fraud_summary.py - generated by convert_rules.py (rule-based, deterministic) from sas/programs/05_card_fraud_summary.sas."""

from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F

spark = SparkSession.builder.master("local[*]").appName("05_card_fraud_summary").getOrCreate()
LIB = {'ctrl': 'data/parquet/ctrl', 'stg': 'data/parquet/stg', 'out': 'data/parquet/py_out/rule_based/run1'}
work = {}  # SAS WORK tables live in memory


def read(lib, table):
    """A table of a SAS library: migrated Parquet (ctrl, stg), a converted output (out) or WORK."""
    if lib == "work":
        return work[table]
    path = f"{LIB[lib]}/{table}" + (".parquet" if lib in ("ctrl", "stg") else "")
    return spark.read.parquet(path)


def save(df, lib, table):
    """Write an `out` table as Parquet; keep a WORK table in memory."""
    if lib == "work":
        work[table] = df
    else:
        df.write.mode("overwrite").parquet(f"{LIB[lib]}/{table}")

# ---- proc means data=stg.card_transactions noprint nway
df = read("stg", "card_transactions").groupBy("merchant_category").agg(F.count("amount").alias("n_txn"), F.sum("amount").alias("total_amount"), F.avg("amount").alias("avg_amount"))
save(df, "out", "card_summary")

# ---- proc freq data=stg.card_transactions noprint
df = read("stg", "card_transactions").dropna(subset=["merchant_category", "fraud_flag"])
total = df.count()
df = df.groupBy("merchant_category", "fraud_flag").agg(F.count(F.lit(1)).alias("count")).withColumn("percent", F.col("count") * 100.0 / total)
save(df, "out", "fraud_freq")
